#!/bin/sh
set -e

echo "Activating feature 'bash-history'"

echo "export PROMPT_COMMAND=\"$BASH_PROMPT_COMMAND\"
HISTFILE=$BASH_HISTFILE
HISTSIZE=$BASH_HISTSIZE
HISTFILESIZE=$BASH_HISTSIZE
HISTTIMEFORMAT=\"$BASH_HISTTIMEFORMAT\"" >> $BASH_RCFILE
