#!/bin/sh
set -e

echo "Activating feature 'zsh-history'"

echo "HISTFILE=$ZSH_HISTFILE
HISTSIZE=$ZSH_HISTSIZE
HISTFILESIZE=$ZSH_HISTSIZE
setopt HIST_IGNORE_ALL_DUPS
setopt INC_APPEND_HISTORY
HISTTIMEFORMAT=\"$ZSH_HISTTIMEFORMAT\"" >> $ZSH_RCFILE 
